name: Push

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  golangci:
    uses: paastech-cloud/.github/.github/workflows/golangci.yml@v2.1

  docker-build-push:
    needs: golangci
    uses: paastech-cloud/.github/.github/workflows/docker.yml@v2.1
    with:
      dockerfile: _docker/Dockerfile.server
      image_name: ${{ github.repository }}
      context: .
